### ISSUE TITLE
Remove -spring.profiles.active from startup config

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/db2rest#154]
This can be done by adding the config below in the application.yml file

```
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
```
